import Head from "next/head";

import { useActivities } from "@/contexts/activities";
import { filterActivities } from "@/lib/filterActivities";

import { Form } from "@/components/form";
import { Grid } from "@/components/grid";
import { Header } from "@/components/header";

export default function Home() {
  const { activities, placesFilter } = useActivities();

  return (
    <>
      <Head>
        <title>Sesc Concerts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Form />
        <Grid items={filterActivities(activities, { places: placesFilter, categories: ["show"] })} />
      </main>
    </>
  );
}
